// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duwdiwknqinqxrlbmdvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1d2Rpd2tucWlucXhybGJtZHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQxMzQsImV4cCI6MjA2NTU2MDEzNH0.xsDf5AQLMQp5nJAjsNVRDAYn4Jj4kLe-TrjKd_alypA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);